CREATE TABLE `im_device_inf` (
                                 `data_center_id` int(11) NOT NULL COMMENT 'Datacenter ID',
                                 `device_id` int(11) NOT NULL COMMENT 'Device ID',
                                 `device_nm` varchar(200) DEFAULT NULL COMMENT 'Device Name',
                                 `device_desc` varchar(2000) DEFAULT NULL COMMENT 'Device Description',
                                 `device_fnc_div_cd` varchar(20) DEFAULT NULL COMMENT '장비기능구분',
                                 `device_use_div_cd` varchar(20) DEFAULT NULL COMMENT '장비용도구분',
                                 `device_category_id` int(11) DEFAULT NULL COMMENT 'Device Category ID',
                                 `device_category_name` varchar(200) DEFAULT NULL COMMENT 'Device Category Name',
                                 `device_type_id` int(11) DEFAULT NULL COMMENT 'Device Type ID',
                                 `device_type_name` varchar(200) DEFAULT NULL COMMENT 'Device Type Name',
                                 `enable_monitor` int(11) DEFAULT NULL COMMENT 'Monitoring Status',
                                 `monitor_start_date` datetime DEFAULT NULL COMMENT 'Monitoring Start Date ',
                                 `monitor_stop_date` datetime DEFAULT NULL COMMENT 'Monitoring Stop Date ',
                                 `device_model_id` int(11) DEFAULT NULL COMMENT 'Device Model ID',
                                 `device_model_name` varchar(200) DEFAULT NULL COMMENT 'Device Model Name',
                                 `maintenance_provider_id` int(11) DEFAULT NULL COMMENT 'Maintenace Provider ID',
                                 `maintenance_provider_name` varchar(200) DEFAULT NULL COMMENT 'Maintenace Provider Name',
                                 `manufacturer_id` int(11) DEFAULT NULL COMMENT 'Device Manufacturer ID',
                                 `manufacturer_name` varchar(200) DEFAULT NULL COMMENT 'Device Manufacturer Name',
                                 `manufactured_date` datetime DEFAULT NULL COMMENT 'Device Manufactu',
                                 `connected_ups` varchar(200) DEFAULT NULL COMMENT '(BMS) Connected UPS Name',
                                 `battery_capacity` int(11) DEFAULT NULL COMMENT '(BMS) Battery Capacity',
                                 `switchboard_branch_count` int(11) DEFAULT NULL COMMENT '(Switchboard) The number of branches',
                                 `location` varchar(200) DEFAULT NULL COMMENT 'Location (Floor > Room > Section)',
                                 `tenants_id` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Customer ID, druid mutil_value 타입을 사용하기 위해 json으로 입력' CHECK (json_valid(`tenants_id`)),
                                 `floor_id` int(11) DEFAULT NULL COMMENT 'Floor ID',
                                 `zone_id` int(11) DEFAULT NULL COMMENT 'Zone ID',
                                 `use_yn` varchar(1) DEFAULT 'Y',
                                 `frst_reg_dt` datetime NOT NULL DEFAULT current_timestamp() COMMENT '최초등록일시',
                                 `frst_reg_user_id` varchar(20) DEFAULT 'admin' COMMENT '최초등록사용자ID',
                                 `last_chg_dt` datetime NOT NULL DEFAULT current_timestamp() COMMENT '최종변경일시',
                                 `last_chg_user_id` varchar(20) DEFAULT 'admin' COMMENT '최종변경사용자ID',
                                 PRIMARY KEY (`data_center_id`,`device_id`),
                                 KEY `idx_r1_dcid_floor_fnc_use` (`data_center_id`,`floor_id`,`device_fnc_div_cd`,`device_use_div_cd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='IM_DEVICE정보'


CREATE TABLE `fm_fault_alarm_cur` (
                                      `dat_seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '데이터순번',
                                      `data_center_id` int(11) NOT NULL,
                                      `id` bigint(20) DEFAULT NULL COMMENT '알람 아이디',
                                      `alarm_policy_name` varchar(255) DEFAULT NULL COMMENT '알람 이름 (내부 이름)',
                                      `alarm_policy_display_name` varchar(255) DEFAULT NULL COMMENT '알람 이름',
                                      `device_id` int(11) DEFAULT NULL COMMENT '장비 아이디',
                                      `device_name` varchar(255) DEFAULT NULL COMMENT '장비 이름',
                                      `checkpoint_id` int(11) DEFAULT NULL COMMENT '성능 아이디',
                                      `checkpoint_name` varchar(255) DEFAULT NULL COMMENT '성능 이름',
                                      `alarm_severity_id` int(11) DEFAULT NULL COMMENT '알람 등급',
                                      `alarm_severity_name` varchar(255) DEFAULT NULL COMMENT '알람 등급 이름',
                                      `confirm_state` varchar(50) DEFAULT NULL COMMENT '알람의 상태 값 아이디',
                                      `confirm_state_name` varchar(50) DEFAULT NULL COMMENT '알람의 상태 값 (미확인, 확인, 종료)',
                                      `log_date` timestamp NULL DEFAULT NULL COMMENT '알람 발생 시간',
                                      `message` text DEFAULT NULL COMMENT '알람 내용',
                                      `acknowledged_date` timestamp NULL DEFAULT NULL COMMENT '인지 처리 시간 (UNIX timestamp)',
                                      `acknowledged_message` varchar(255) DEFAULT NULL COMMENT '인지 처리 내용',
                                      `closed_date` timestamp NULL DEFAULT NULL COMMENT '종료 처리 시간 (UNIX timestamp)',
                                      `closed_message` text DEFAULT NULL COMMENT '종료 처리 내용 (JSON 배열)',
                                      `frst_reg_dt` datetime NOT NULL DEFAULT current_timestamp() COMMENT '최초등록일시',
                                      `frst_reg_user_id` varchar(20) DEFAULT 'admin' COMMENT '최초등록사용자ID',
                                      `last_chg_dt` datetime NOT NULL DEFAULT current_timestamp() COMMENT '최종변경일시',
                                      `last_chg_user_id` varchar(20) DEFAULT 'admin' COMMENT '최종변경사용자ID',
                                      PRIMARY KEY (`dat_seq`),
                                      UNIQUE KEY `fm_fault_alarm_cur_pk` (`data_center_id`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=274354518 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='IM_장애알람현재'


CREATE TABLE `fm_fault_alarm_his` (
                                      `dat_seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '데이터순번',
                                      `data_center_id` int(11) NOT NULL,
                                      `id` bigint(20) NOT NULL COMMENT '알람 아이디',
                                      `alarm_policy_name` varchar(255) DEFAULT NULL COMMENT '알람 이름 (내부 이름)',
                                      `alarm_policy_display_name` varchar(255) DEFAULT NULL COMMENT '알람 이름',
                                      `device_id` int(11) DEFAULT NULL COMMENT '장비 아이디',
                                      `device_name` varchar(255) DEFAULT NULL COMMENT '장비 이름',
                                      `checkpoint_id` int(11) DEFAULT NULL COMMENT '성능 아이디',
                                      `checkpoint_name` varchar(255) DEFAULT NULL COMMENT '성능 이름',
                                      `alarm_severity_id` int(11) DEFAULT NULL COMMENT '알람 등급',
                                      `alarm_severity_name` varchar(255) DEFAULT NULL COMMENT '알람 등급 이름',
                                      `confirm_state` varchar(50) DEFAULT NULL COMMENT '알람의 상태 값 아이디',
                                      `confirm_state_name` varchar(50) DEFAULT NULL COMMENT '알람의 상태 값 (미확인, 확인, 종료)',
                                      `log_date` timestamp NOT NULL COMMENT '알람 발생 시간 (UNIX timestamp)',
                                      `message` text DEFAULT NULL COMMENT '알람 내용',
                                      `acknowledged_date` timestamp NULL DEFAULT NULL COMMENT '인지 처리 시간 (UNIX timestamp)',
                                      `acknowledged_message` varchar(255) DEFAULT NULL COMMENT '인지 처리 내용',
                                      `closed_date` timestamp NULL DEFAULT NULL COMMENT '종료 처리 시간 (UNIX timestamp)',
                                      `closed_message` text DEFAULT NULL COMMENT '종료 처리 내용 (JSON 배열)',
                                      `frst_reg_dt` datetime NOT NULL DEFAULT current_timestamp() COMMENT '최초등록일시',
                                      `frst_reg_user_id` varchar(20) DEFAULT 'admin' COMMENT '최초등록사용자ID',
                                      `last_chg_dt` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                                      `last_chg_user_id` varchar(20) DEFAULT 'admin' COMMENT '최종변경사용자ID',
                                      PRIMARY KEY (`dat_seq`,`log_date`),
                                      UNIQUE KEY `fm_fault_alarm_his_pk` (`data_center_id`,`id`,`log_date`)
) ENGINE=InnoDB AUTO_INCREMENT=274358441 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='IM_장애알람이력'
 PARTITION BY RANGE (unix_timestamp(`log_date`))
(PARTITION `p20260121` VALUES LESS THAN (1769007600) ENGINE = InnoDB,
 PARTITION `p20260122` VALUES LESS THAN (1769094000) ENGINE = InnoDB,
 PARTITION `p20260123` VALUES LESS THAN (1769180400) ENGINE = InnoDB,
 PARTITION `p20260124` VALUES LESS THAN (1769266800) ENGINE = InnoDB,
 PARTITION `p20260125` VALUES LESS THAN (1769353200) ENGINE = InnoDB,
 PARTITION `p20260126` VALUES LESS THAN (1769439600) ENGINE = InnoDB,
 PARTITION `p20260127` VALUES LESS THAN (1769526000) ENGINE = InnoDB,
 PARTITION `p20260128` VALUES LESS THAN (1769612400) ENGINE = InnoDB,
 PARTITION `p20260129` VALUES LESS THAN (1769698800) ENGINE = InnoDB,
 PARTITION `p20260130` VALUES LESS THAN (1769785200) ENGINE = InnoDB,
 PARTITION `p20260131` VALUES LESS THAN (1769871600) ENGINE = InnoDB,
 PARTITION `p20260201` VALUES LESS THAN (1769958000) ENGINE = InnoDB,
 PARTITION `p20260202` VALUES LESS THAN (1770044400) ENGINE = InnoDB,
 PARTITION `p20260203` VALUES LESS THAN (1770130800) ENGINE = InnoDB,
 PARTITION `p20260204` VALUES LESS THAN (1770217200) ENGINE = InnoDB,
 PARTITION `p20260205` VALUES LESS THAN (1770303600) ENGINE = InnoDB,
 PARTITION `p20260206` VALUES LESS THAN (1770390000) ENGINE = InnoDB,
 PARTITION `p20260207` VALUES LESS THAN (1770476400) ENGINE = InnoDB,
 PARTITION `p20260208` VALUES LESS THAN (1770562800) ENGINE = InnoDB,
 PARTITION `p20260209` VALUES LESS THAN (1770649200) ENGINE = InnoDB,
 PARTITION `p20260210` VALUES LESS THAN (1770735600) ENGINE = InnoDB,
 PARTITION `p20260211` VALUES LESS THAN (1770822000) ENGINE = InnoDB,
 PARTITION `p20260212` VALUES LESS THAN (1770908400) ENGINE = InnoDB,
 PARTITION `p20260213` VALUES LESS THAN (1770994800) ENGINE = InnoDB,
 PARTITION `p20260214` VALUES LESS THAN (1771081200) ENGINE = InnoDB)
